### ISSUE TITLE
Compile on Mac OS (M1) passes, but results in unusable executable

### ISSUE THREAD

**Issue by MathiasWedeken** [gisogrimm/ovbox#2]
After successfully cloning the repo, installing deps  and running "make", the starting the executable in "/build", I get this console message: 

`Error: unable to open jack client: Overall operation failed. Unable to connect to the JACK server. `  

Interestingly, I've used a precompiled intel build before that initially gave me this: 

`Device error:
Unable to open module "route": dlopen(/private/var/folders/d0/hy3dnngn0q79n9s7fnt4td6r0000gn/T/AppTranslocation/78AE5BBC-F29B-44E2-8755-7A661F5D6C05/d/ovbox.app/Contents/MacOS/lib/ovclienttascar_route.dylib, 0x0002): cannot dlopen until fork() handlers have completed`

And after compiling, that same intel build gave the same error message as the M1 executable. 

System is a 16inch Macbook Pro M1Pro 2021, with no external audio device (problem shows up with external audio device as well)

**Comment by gisogrimm** [comment]
On MacOS it is neccessary to setup the library paths. For example see the shell scripts `start_ovbox.sh` (for the GUI application) and `start_ov-client.sh` (for the command line application). These are meant to start the locally compiled binaries:
```
cd ~/ov-client
./start_ovbox.sh
```
Similarly, the pre-compiled version needs to find its paths. Here the situation is a bit more complex, because it is a sandboxed installation which partly depends on system-wide installs (specifically jack, which, depending on the installation method, is installed either manually or via brew and can be found in various alternativ locations). To see how this is started please see the file `packaging/Darwin/ovboxwrapper` (this is installed as `ovbox` in the packaged version).

**Comment by gisogrimm** [comment]
The current repository for the source code is [https://github.com/gisogrimm/ov-client/](https://github.com/gisogrimm/ov-client/), this repository is kept for documentation only.

**Comment by MathiasWedeken** [comment]
@gisogrimm Cool, using the startup scripts worked. Thanks, and sorry if I missed that bit in the docs.

**Comment by gisogrimm** [comment]
I added this bit of information to the wiki pages: https://github.com/gisogrimm/ovbox/wiki/Installation#compile-yourself
